/* constant create session  */
export const CREATE_USER_REQUEST_TOKEN = 'CREATE_USER_REQUEST_TOKEN';
export const CREATE_USER_REQUEST_TOKEN_PENDING = 'CREATE_USER_REQUEST_TOKEN_PENDING';
export const CREATE_USER_REQUEST_TOKEN_SUCCESS = 'CREATE_USER_REQUEST_TOKEN_SUCCESS';
export const CREATE_USER_REQUEST_TOKEN_ERRORED = 'CREATE_USER_REQUEST_TOKEN_ERRORED';

/* constant login user with session  */
export const USER_LOGIN_WITH_SESSION = 'USER_LOGIN_WITH_SESSION';
export const USER_LOGIN_WITH_SESSION_PENDING = 'USER_LOGIN_WITH_SESSION_PENDING';
export const USER_LOGIN_WITH_SESSION_SUCCESS = 'USER_LOGIN_WITH_SESSION_SUCCESS';
export const USER_LOGIN_WITH_SESSION_ERRORED = 'USER_LOGIN_WITH_SESSION_ERRORED';

/* constant logout with session  */
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_PENDING = 'USER_LOGOUT_PENDING';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_ERRORED = 'USER_LOGIN_ERRORED';